use ncurses;

pub type Key = i32;

pub const LEFT:  Key = ncurses::KEY_LEFT;
pub const RIGHT: Key = ncurses::KEY_RIGHT;
pub const UP:    Key = ncurses::KEY_UP;
pub const DOWN:  Key = ncurses::KEY_DOWN;

pub const BACKSPACE: Key = ncurses::KEY_BACKSPACE;
pub const ENTER:     Key = ncurses::KEY_ENTER;

pub const LOWER_A: Key = 'a' as i32;
pub const LOWER_B: Key = 'b' as i32;
pub const LOWER_C: Key = 'c' as i32;
pub const LOWER_D: Key = 'd' as i32;
pub const LOWER_E: Key = 'e' as i32;
pub const LOWER_F: Key = 'f' as i32;
pub const LOWER_G: Key = 'g' as i32;
pub const LOWER_H: Key = 'h' as i32;
pub const LOWER_I: Key = 'i' as i32;
pub const LOWER_J: Key = 'j' as i32;
pub const LOWER_K: Key = 'k' as i32;
pub const LOWER_L: Key = 'l' as i32;
pub const LOWER_M: Key = 'm' as i32;
pub const LOWER_N: Key = 'n' as i32;
pub const LOWER_O: Key = 'o' as i32;
pub const LOWER_P: Key = 'p' as i32;
pub const LOWER_Q: Key = 'q' as i32;
pub const LOWER_R: Key = 'r' as i32;
pub const LOWER_S: Key = 's' as i32;
pub const LOWER_T: Key = 't' as i32;
pub const LOWER_U: Key = 'u' as i32;
pub const LOWER_V: Key = 'v' as i32;
pub const LOWER_W: Key = 'w' as i32;
pub const LOWER_X: Key = 'x' as i32;
pub const LOWER_Y: Key = 'y' as i32;
pub const LOWER_Z: Key = 'z' as i32;

pub const UPPER_A: Key = 'A' as i32;
pub const UPPER_B: Key = 'B' as i32;
pub const UPPER_C: Key = 'C' as i32;
pub const UPPER_D: Key = 'D' as i32;
pub const UPPER_E: Key = 'E' as i32;
pub const UPPER_F: Key = 'F' as i32;
pub const UPPER_G: Key = 'G' as i32;
pub const UPPER_H: Key = 'H' as i32;
pub const UPPER_I: Key = 'I' as i32;
pub const UPPER_J: Key = 'J' as i32;
pub const UPPER_K: Key = 'K' as i32;
pub const UPPER_L: Key = 'L' as i32;
pub const UPPER_M: Key = 'M' as i32;
pub const UPPER_N: Key = 'N' as i32;
pub const UPPER_O: Key = 'O' as i32;
pub const UPPER_P: Key = 'P' as i32;
pub const UPPER_Q: Key = 'Q' as i32;
pub const UPPER_R: Key = 'R' as i32;
pub const UPPER_S: Key = 'S' as i32;
pub const UPPER_T: Key = 'T' as i32;
pub const UPPER_U: Key = 'U' as i32;
pub const UPPER_V: Key = 'V' as i32;
pub const UPPER_W: Key = 'W' as i32;
pub const UPPER_X: Key = 'X' as i32;
pub const UPPER_Y: Key = 'Y' as i32;
pub const UPPER_Z: Key = 'Z' as i32;
